#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=50
USE_PROCD=1

PROG=/usr/bin/auth_server

start_service() {
        procd_open_instance
        procd_set_param command $PROG
        procd_set_param respawn
        procd_close_instance
}
